# Generated by Django 3.0.5 on 2020-04-11 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
