# Generated by Django 3.0.5 on 2020-04-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapi', '0002_auto_20200411_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
