# Generated by Django 3.0.5 on 2020-04-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_journalist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalist',
            old_name='bigraphy',
            new_name='biography',
        ),
    ]
